### ISSUE TITLE
Remove menu options

### ISSUE THREAD

**Issue by Fleker** [Fleker/WebGameBridge.js#9]
The current activity has menus, but these should be removed as they aren't needed.

**Comment by eternalBlast** [comment]
Hello @Fleker  i want to contribute to this project

**Comment by Fleker** [comment]
Great! Thanks!

**Comment by eternalBlast** [comment]
When i run this project, in the beginning, the app is connecting to google play and i confirmed the dialog. When it is done, the ProgressBar keeps appearing and won't dismiss. Also, the line import com.felkertech.n.queuify.R; cannot find the package.

**Comment by Fleker** [comment]
Seems like there's some error in connecting to Google Play. Check the logs to see if there's some response in the connection error method. Are you using the debug version? There could be an issue with certain types of access to Google Play Games.

The line import shouldn't break anything.

**Comment by eternalBlast** [comment]
Yes, i used the debug variant. I checked the log and found this error. libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY). FYI, i used Lollipop device.

**Comment by Fleker** [comment]
It's been a while since I've updated the game. I'll take another look at this and make sure there's nothing weird happening.

**Comment by Fleker** [comment]
Okay the issue is coming from Google Play Services: http://stackoverflow.com/questions/28189617/google-play-services-resultcode-10004

You would need to send a valid keystore for the project so that the configuration is valid.

With regards to this specific issue, it was just removing some unneeded resources. This issue will be closed, but you can take a look at some of the other issues in this repo if you're still interested.
